name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libpcre and luajit
        run: sudo apt-get install -y libluajit-5.1-dev luajit libpcre3-dev

      - name: Install cmake-js for building node bindings"
        run: "npm install cmake-js -g"

      - name: "Install Denim for building node bindings"
        run: "nimble install -y denim"

      - name: "Install & test via Nimble"
        run: |
          nimble install -Y
          nimble test

      - name: "Build a Node addon via Denim"
        run: denim build src/${{ github.event.repository.name }}.nim -r -y --cmake